[variables]
NODE_VERSION = "22.12.0"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build"

[start]
cmd = "npx http-server dist/angular-auth-app -p $PORT -c-1"
